version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: chatbot-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: chatbot-backend
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
